language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk8
    - os: linux
      dist: precise
      sudo: false
      jdk: oraclejdk8
    - os: osx

before_install:
  - '[[ "$encrypted_7aff20607abf_key" != "" && "$encrypted_7aff20607abf_iv" != "" ]] && openssl aes-256-cbc -K $encrypted_7aff20607abf_key -iv $encrypted_7aff20607abf_iv -in gradle-travis.properties.enc -out $HOME/.gradle/gradle.properties -d || true'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then jdk install oraclejdk8; fi'

install: ./gradlew clean

script:
  - ./gradlew assemble
  - ./gradlew check

after_script:
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == bit3/jsass ]] && [[ $TRAVIS_BRANCH == develop ]] && ./gradlew sonarqube -x test"
